---
language: elixir
sudo: required
dist: trusty
addons:
  postgresql: "9.5"
services:
  - postgresql
before_script:
  - psql -c 'create database walL_test;' -U postgres
  - npm install
elixir:
  - 1.3.2
otp_release:
  - 19.0
script:
  - bin/test
